[package]
name = "soji"
version = "0.4.4"
description = "Soji is a performant Rust-Tauri sticker picker for Windows 11. "
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "soji_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
window-vibrancy = "0.7.1"
tauri-plugin-global-shortcut = "2.3.1"
tauri-plugin-fs = "2.4.4"
tauri-plugin-store = "2.4.1"
walkdir = "2.5.0"
arboard = "3.6.1"
image = "0.25.9"
enigo = "0.6.1"
clipboard-win = "5.4.1"
fuzzy-matcher = "0.3.7"
chrono = "0.4.42"
tauri-plugin-dialog = "2.4.2"
rusqlite = { version = "0.38.0", features = ["bundled"] }
fast_image_resize = "5.4.0"
sha2 = "0.10.9"
hex = "0.4.3"
tokio = "1.48.0"
rayon = "1.11.0"
notify = "6.1.1"
tauri-plugin-autostart = "2.5.1"
tauri-plugin-updater = "2.9.0"
tauri-plugin-process = "2.3.1"
reqwest = { version = "0.13.1", features = ["blocking", "rustls-native-certs"] }
infer = "0.19.0"
uuid = { version = "1.19.0", features = ["v4", "fast-rng"] }
url = "2.5.8"
urlencoding = "2.1.3"

[profile.release]
codegen-units = 1
lto = "thin"      
strip = true      
panic = "abort"   
